### ISSUE TITLE
Cross-Class Skills - API: negative-value buffs do not seem to be allowed anymore

### ISSUE THREAD

**Issue by Futeko** [mike-the-monk/Habitica-customizations#6]
I'm using the Cross-Class "Burst of Flames (XP and Damage)" skill, and recently I've encountered an issue where it does not do damage anymore.

After debugging the issue, I've noticed that the following call in the "doDamage" function fails:
`api_updateUser({"stats.buffs.str" : setpoint - unbuffedStr, "stats.buffs.int" : 1 - unbuffedInt, "stats.buffs.per" : 1 - unbuffedPer})`

The returned response mentions:
```
success=[false]
error=[BadRequest]
message=[User validation failed]
errors[1].message=[Path stats.buffs.int (-205.5) is less than minimum allowed value (0).]
```

And indeed, it seems the API does not accept a negative value for stats.buffs variables anymore. I can set them to 0, but not to a value <0.

It does not look trivial to fix because the logic was to set INT & PER to 1 - but without a negative-value buff, we're looking at quite complex calls as we'd need to not only set the user's buffs to 0, but also their level to 1, stat-allocation to 0, and unequip all items (and reverse those changes afterwards).

My question would thus be - is there actually an added value to setting INT & PER to 1 in that function?
My understanding is that:
* Ticking off the damage task will award gold & xp based on INT & PER
* But we anyway reset them to their previous state at the end of the function, with their values modified only by the calculated MP cost & exp gain from the skill.
* So does it really matter if INT & PER keep their original value?

I've tested an update of the script where we do not touch the buff values, we only update the STR buff - and it seems to work just like before with regards to damage, gold & xp gain.

Could you please confirm I'm not missing anything?
If so I can create a pull request with my update suggestion.

**Comment by mike-the-monk** [comment]
Stat buffs to only allow for positive values. I knew it would break something in my scripts but I wasn't quite sure how they would react.

I'm glad you tested it and discovered it doesn't actually matter if we set INT and PER to 1. I suspected that might be the case because the script also saves GP/XP values so that any GP and XP gain from checking off the task gets reverted to the old value.

Where I could see a potential problem is if someone is close to leveling up, the XP gain from the task that the script checks off causes them to level up, and then the script reverts the XP value to the old value (i.e. close to leveling up) and so basically they got an entire level's worth of XP for free. I bet it's possible to save Level along with GP and XP, and then have the script revert it back to the previous value.

It will be annoying to re-factor all of the functions, though.

**Comment by Futeko** [comment]
Doesn't the script already save and restore level after applying damage?

```
api_updateUser({"stats.buffs.str" : buffsStr, "stats.buffs.int" : buffsInt, "stats.buffs.per" : buffsPer,
                    "stats.hp" : hp, "stats.exp" : xp, "stats.mp" : mp - totalMpCost, "stats.gp" : gp, "stats.lvl" : lvl})
```

It seems to me it saves & restore anything that could be affected by the task (XP, Gold, Level) so it would not matter whether you are close to leveling up or not - even if the task got you e.g. from Lv68 & 1990 Exp to Lv69 & 10 Exp, the script will anyway reset you to Lv68 & 1990 Exp (not Lv69 & 1990 Exp).

**Comment by mike-the-monk** [comment]
Whoops, totally forgot I did that. Good catch.

So, you should be all good to go on proposing whatever changes you want.

**Comment by Futeko** [comment]
Haha, all right! I've created a pull request with the suggested changes.
